[package]
name = "rtracer_cpu"
version = "0.1.0"
authors = ["Pavel <pavilbezpravil@gmail.com>"]
edition = "2018"

[dependencies]
rtracer_core = { path = "../rtracer_core" }
rand = "*"
rayon = "*"
itertools = "*"
approx = "*"