[package]
name = "rtracer"
version = "0.1.0"
authors = ["Pavel <pavilbezpravil@gmail.com>"]
edition = "2018"

[dependencies]
rtracer_core = { path = "rtracer_core" }
rtracer_cpu = { path = "rtracer_cpu" }
rtracer_gpu = { path = "rtracer_gpu" }

rand = "*"
winit = "0.18"
