[package]
name = "rtracer"
version = "0.1.0"
authors = ["Pavel <pavilbezpravil@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
rayon = "*"
itertools = "*"
serde = { version = "*", features = ["derive", "rc"] }
serde_json = "*"
approx = "*"