[package]
name = "rtracer_gpu"
version = "0.1.0"
authors = ["Pavel <pavilbezpravil@gmail.com>"]
edition = "2018"

[dependencies]
rtracer_core = { path = "../rtracer_core" }

vulkano = "0.12"
vulkano-shaders = "0.12"
vulkano-win = "0.12"
winit = "0.19"

image = "0.21"
rand = "*"